### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/nuxt-build-banner#4]
The IBM Sans fonts are not imported in the Nuxt `module.ts` 

Also, they are wrongly used in the component.

```css
* {
  font-family: 'IBM Plex Sans'; /* this should be named IBM Sans as defined in the typography.css */
  font-size: 18px;
}
```

As well as there are fonts imported and defined in the `typography.css` that are not avaiable in the `fonts` directory.

References
[Nuxt3 Module Assets Injection](https://nuxt.com/docs/guide/going-further/modules#injecting-other-assets)
